spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
image:
  base: ${user.dir}
  type:
    post: post
    profile: profile